name: Docker Integration CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: create env file
      run: |
        echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> .env
        echo "PORT=8000" >> .env

    - name: Build and run Docker containers
      run: docker compose up --build -d

    - name: Check container status
      run: |
        sleep 5
        docker compose ps
        
    - name: Run tests inside container
      run: docker compose exec -T server pytest

    - name: Dump docker logs on failure
      if: failure()
      run: docker compose logs